/**
 * Export and Download Utilities
 */

export function exportToJson(data, filename = "startup-intelligence-report.json") {
  const jsonStr = JSON.stringify(data, null, 2);
  const blob = new Blob([jsonStr], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportPitchDeckMarkdown(report) {
  if (!report || !report.pitch || !report.pitch.slides) return;
  const name = report.meta?.startupName || "Startup";
  
  let md = `# ${name} — Investor Pitch Deck\n\n`;
  md += `**Tagline:** ${report.meta?.tagline || ""}\n`;
  md += `**Viability Score:** ${report.score?.overallScore || "N/A"}/100 (${report.score?.tier || ""})\n\n`;
  md += `---\n\n`;

  report.pitch.slides.forEach((slide) => {
    md += `## Slide ${slide.slideNumber}: ${slide.title}\n\n`;
    md += `### *${slide.headline}*\n\n`;
    if (slide.bullets && slide.bullets.length) {
      slide.bullets.forEach((b) => {
        md += `- ${b}\n`;
      });
    }
    if (slide.speakerNotes) {
      md += `\n> **Speaker Notes:** ${slide.speakerNotes}\n\n`;
    }
    md += `---\n\n`;
  });

  if (report.pitch.elevatorPitch) {
    md += `## Executive Elevator Pitch\n\n${report.pitch.elevatorPitch}\n`;
  }

  const blob = new Blob([md], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${name.toLowerCase().replace(/\s+/g, "-")}-pitch-deck.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function copyMarkdownSummary(report) {
  if (!report) return false;
  const name = report.meta?.startupName || "Startup";

  let summary = `# ${name} — AI Intelligence Dossier\n\n`;
  summary += `**Score:** ${report.score?.overallScore}/100 | **Tier:** ${report.score?.tier}\n`;
  summary += `**Industry:** ${report.meta?.industry} | **Stage:** ${report.meta?.stage}\n\n`;

  summary += `## Executive Summary\n`;
  summary += `${report.executive?.opportunityOverview || ""}\n\n`;
  summary += `**Problem:** ${report.executive?.problemStatement || ""}\n\n`;
  summary += `**Solution:** ${report.executive?.solutionStatement || ""}\n\n`;
  summary += `**Value Prop:** ${report.executive?.valueProposition || ""}\n\n`;
  summary += `**AI Verdict:** ${report.executive?.aiVerdict?.recommendation || "N/A"} — ${report.executive?.aiVerdict?.headline || ""}\n\n`;

  summary += `## Market Sizing\n`;
  summary += `- **TAM:** ${report.market?.tam?.value || "N/A"} (${report.market?.tam?.geography || ""})\n`;
  summary += `- **SAM:** ${report.market?.sam?.value || "N/A"}\n`;
  summary += `- **SOM:** ${report.market?.som?.value || "N/A"}\n`;
  summary += `- **CAGR:** ${report.market?.cagr || "N/A"}\n\n`;

  summary += `Generated by AI Co-Founder Platform\n`;

  try {
    await navigator.clipboard.writeText(summary);
    return true;
  } catch (err) {
    console.error("Clipboard copy failed:", err);
    return false;
  }
}

export function printReport() {
  window.print();
}
